//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Mis9.Dmini.Bll.ERPService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="fyjSoap", Namespace="http://tempuri.org/")]
    public partial class fyj : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaleListOperationCompleted;
        
        private System.Threading.SendOrPostCallback outpOrderCompletionNotifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback outpBatchenoOperationCompleted;
        
        private System.Threading.SendOrPostCallback outWareOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public fyj() {
            this.Url = global::Mis9.Dmini.Bll.Properties.Settings.Default.Mis9_Dmini_Bll_ERPService_fyj;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaleListCompletedEventHandler SaleListCompleted;
        
        /// <remarks/>
        public event outpOrderCompletionNotifyCompletedEventHandler outpOrderCompletionNotifyCompleted;
        
        /// <remarks/>
        public event outpBatchenoCompletedEventHandler outpBatchenoCompleted;
        
        /// <remarks/>
        public event outWareCompletedEventHandler outWareCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaleList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaleList(string json) {
            object[] results = this.Invoke("SaleList", new object[] {
                        json});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SaleListAsync(string json) {
            this.SaleListAsync(json, null);
        }
        
        /// <remarks/>
        public void SaleListAsync(string json, object userState) {
            if ((this.SaleListOperationCompleted == null)) {
                this.SaleListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaleListOperationCompleted);
            }
            this.InvokeAsync("SaleList", new object[] {
                        json}, this.SaleListOperationCompleted, userState);
        }
        
        private void OnSaleListOperationCompleted(object arg) {
            if ((this.SaleListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaleListCompleted(this, new SaleListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/outpOrderCompletionNotify", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int outpOrderCompletionNotify(string xml) {
            object[] results = this.Invoke("outpOrderCompletionNotify", new object[] {
                        xml});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void outpOrderCompletionNotifyAsync(string xml) {
            this.outpOrderCompletionNotifyAsync(xml, null);
        }
        
        /// <remarks/>
        public void outpOrderCompletionNotifyAsync(string xml, object userState) {
            if ((this.outpOrderCompletionNotifyOperationCompleted == null)) {
                this.outpOrderCompletionNotifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnoutpOrderCompletionNotifyOperationCompleted);
            }
            this.InvokeAsync("outpOrderCompletionNotify", new object[] {
                        xml}, this.outpOrderCompletionNotifyOperationCompleted, userState);
        }
        
        private void OnoutpOrderCompletionNotifyOperationCompleted(object arg) {
            if ((this.outpOrderCompletionNotifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.outpOrderCompletionNotifyCompleted(this, new outpOrderCompletionNotifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/outpBatcheno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string outpBatcheno(string xml) {
            object[] results = this.Invoke("outpBatcheno", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void outpBatchenoAsync(string xml) {
            this.outpBatchenoAsync(xml, null);
        }
        
        /// <remarks/>
        public void outpBatchenoAsync(string xml, object userState) {
            if ((this.outpBatchenoOperationCompleted == null)) {
                this.outpBatchenoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnoutpBatchenoOperationCompleted);
            }
            this.InvokeAsync("outpBatcheno", new object[] {
                        xml}, this.outpBatchenoOperationCompleted, userState);
        }
        
        private void OnoutpBatchenoOperationCompleted(object arg) {
            if ((this.outpBatchenoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.outpBatchenoCompleted(this, new outpBatchenoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/outWare", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string outWare(string xml) {
            object[] results = this.Invoke("outWare", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void outWareAsync(string xml) {
            this.outWareAsync(xml, null);
        }
        
        /// <remarks/>
        public void outWareAsync(string xml, object userState) {
            if ((this.outWareOperationCompleted == null)) {
                this.outWareOperationCompleted = new System.Threading.SendOrPostCallback(this.OnoutWareOperationCompleted);
            }
            this.InvokeAsync("outWare", new object[] {
                        xml}, this.outWareOperationCompleted, userState);
        }
        
        private void OnoutWareOperationCompleted(object arg) {
            if ((this.outWareCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.outWareCompleted(this, new outWareCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SaleListCompletedEventHandler(object sender, SaleListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaleListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaleListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void outpOrderCompletionNotifyCompletedEventHandler(object sender, outpOrderCompletionNotifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class outpOrderCompletionNotifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal outpOrderCompletionNotifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void outpBatchenoCompletedEventHandler(object sender, outpBatchenoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class outpBatchenoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal outpBatchenoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void outWareCompletedEventHandler(object sender, outWareCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class outWareCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal outWareCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591